<?php

function custom_notifications_menu(){
    $items['notification'] = array(
        'title' 		   => 'Notifications',
        'description' 	   => 'Notificaitons Page',
        'page callback'    => 'notifications',
        'access callback' => TRUE,
    );
	
    return $items;
}


function custom_notifications_menu_alter(&$items) {
	 $items['notification']['access callback'] = 'user_logged_in_uac';
}


function user_logged_in_uac(){
	global $user;
	
	if($user->uid != 0) 
		return TRUE;
	else 
		return false;
}

function notifications() {
	global $user;
	
	$result  = db_select('notifications', 'n')
	->fields('n')
	->condition("n.uid", $user->uid, "=")
	->execute();
		
	$data = $result;
	$theme = theme('notifications', array('data' => $data));
	
	db_update('notifications') 
		->fields(array(
		  'is_new' => 0,
		))
		->condition("uid", $user->uid, "=")
		->condition("is_new", 1, "=")
		->execute();	
	
	return $theme;
}


//called in preproccess page on template.php
function check_new_notification() {
	global $user;
	
	$result = db_select('og_membership', 'm');
	$result->join('field_data_opigno_user_membership_exp', 'me', 'm.id = me.entity_id');
	$result->join('node', 'n', 'n.nid = m.gid');
	
	$result = $result->fields('m', array('gid'))
	->fields('me', array('entity_id', 'opigno_user_membership_exp_value'))
	->fields('n', array('title'))
    ->condition('m.etid', $user->uid, '=')
    ->condition('m.entity_type', 'user', '=')
    ->execute();
	
	$near_expiration_courses = "";
	
	foreach ($result as $row) {
		
		$date1 = new DateTime(date("Y-m-d"));
		$date2 = new DateTime(date("Y-m-d", strtotime($row->opigno_user_membership_exp_value)));
		$interval = $date1->diff($date2);
		
		//check if course is about to expired
		if($interval->days <= 14) {
			$row->expiration_days =  $interval->days;
			$near_expiration_courses[] = $row;
			//dpm($row);
			//dpm( "difference " . $interval->days . " days ");
		}
	}
	
	foreach($near_expiration_courses as $notif) {
		$result  = db_select('notifications', 'n')
		->fields('n')
		->condition("n.uid", $user->uid, "=")
		->condition("n.course_id", $notif->gid, "=")
		->condition("n.expiration_date", date("Y-m-d", strtotime($notif->opigno_user_membership_exp_value)), "=")
		->condition("n.expiration_days", $notif->expiration_days, "=")
		->execute();
		
		if(!$result->fetchAssoc()) {
			db_insert('notifications') 
			->fields(array(
			  'uid' => $user->uid,
			  'course_id' => $notif->gid,
			  'expiration_date' => date("Y-m-d", strtotime($notif->opigno_user_membership_exp_value)),
			  'expiration_days' => $notif->expiration_days,
			  'is_new' => 1,
			  'date_created' => date("Y-m-d h:i"),
			))
			->execute();	
		}
	}
}


function custom_notifications_theme($existing, $type, $theme, $path) {
    $items['notifications'] = array(
        'render element' => 'form',
        'template' => 'notifications',
        'variables' => array(
			"data" => NULL
		),
        'path' => drupal_get_path('module', 'custom_notifications').'/template'
    );
	
    return $items;
}


