<?php $course_quizzes = _daisyflo_get_scores($view->args[0], $user->uid);?><?php $course_quizzes = $course_quizzes['courses'][$view->args[0]];?><?php $df_quiz_type = 'THEORY and QUIZ';?><?php $rows = 5; $rendered_take = FALSE; ?>    <?php if (isset($passed_quiz)) $rows++; ?>    <?php if (isset($quiz_type[LANGUAGE_NONE][0]['value'])): ?>    <?php $rows++; $rendered_take = TRUE; ?>    <?php switch($quiz_type[LANGUAGE_NONE][0]['value']) {         case 'quiz':         	$df_quiz_type = 'QUIZ';           break;         case 'theory':         	$df_quiz_type = 'THEORY';            break;         default:             break;       } ?>
       <?php $link = menu_get_item("node/{$node->nid}");?>       <?php 
		$read_more = "";        if (!empty($link) && $link['access'] && !($page)) {            $read_more = l(t("Read more"), "node/{$node->nid}", array('attributes' => array('class' => array('btn', 'btn-primary'))));        }
        $link = menu_get_item("node/{$node->nid}/edit");
        Global $user;
        if (node_access('update', $node,$user)) {          print l(t("Edit"), "node/{$node->nid}/edit", array('attributes' => array('class' => array('edit', 'action-element', 'action-edit-element'))));        }
        $link = menu_get_item("node/{$node->nid}/questions");
        if (!empty($link) && $link['access']) {
           print l(t("Manage questions"), "node/{$node->nid}/questions", array('attributes' => array('class'=> array('question', 'action-element', 'action-question-element'))));   
         }
         $link = menu_get_item("node/{$node->nid}/results");
         if (!empty($link) && $link['access']) {
           print l(t("Results"), "node/{$node->nid}/results", array('attributes' => array('class' => array('results', 'action-element', 'action-results-element'))));
          }          ?>  <?php endif; ?><?php if (!$rendered_take): ?>	<?php //print render($content['take']); ?>	<?php if (!$page): ?>		<?php $read_more = l(t("Read more"), "node/{$node->nid}", array('attributes' => array('class' => array('btn', 'btn-primary')))); ?>	<?php endif; ?><?php endif; ?><?php //$node = node_load(arg(1));?><div class="panel-body">	<?php $cover_img = file_create_url($node->field_cover_image['und'][0]['uri'])?>	<div class="col-lg-2 course-thumbnail-placeholder" 			style="background-image: url('<?php print strip_tags($cover_img);?>')">	</div>	<div class="col-lg-10 course-card-info">		<div class="course-card-score-info col-lg-12">			<span class="col-lg-2 no-padding <?php print $df_quiz_type?>">				<bold><?php print $df_quiz_type?></bold>			</span>			<?php if ($quiz_type[LANGUAGE_NONE][0]['value'] == 'theory'):?>				 <?php if (isset($passed_quiz)): ?>			    	 <?php if ($passed_quiz): ?>			           <span class="col-lg-10">Completed</span>			         <?php else:?>			           <span class="col-lg-10">Not Completed</span>			        <?php endif; ?>		        <?php endif; ?>		    <?php else:?>		        <?php if (isset($passed_quiz)): ?>		           <?php if ($passed_quiz): ?>			            <span class="col-lg-10">Passed</span>			         <?php else:?>			           <span class="col-lg-10">Not Completed</span>			       <?php endif; ?>		        <?php endif; ?>			<?php endif; ?>		</div>		<h3 class="course-card-header"><?php print $title; ?></h3>		<div class="col-lg-7">			<div class="course-card-body">				<?php $body = field_view_field('node', $node, 'body');?>				<?php if ($quiz_type[LANGUAGE_NONE][0]['value'] == 'quiz'):?>					<ul>						<li>Questions: <?php print $node->number_of_random_questions + _quiz_get_num_always_questions($node->vid); ?></li>						<li>Pass Rate:  <?php print $node->pass_rate; ?>%</li>					</ul>				<?php else:?>					<?php print render($body)?>				<?php endif;?>			</div>		</div>		<div class="col-lg-5">			<div class="card-actions">				<?php $progress = _daisyflo_get_course_progress($fields['nid']->raw, $user->uid);?>				<span class="btn btn-secondary">					<span><a href="/node/<?php print $node->nid?>">Read More</a></span>				</span>				<?php if ($course_quizzes[$node->vid]->percent_score !== null):?>					<span class="btn btn-primary">						<a href="/node/<?php print $node->nid?>/take">Continue</a>					</span>				<?php else:?>					<span class="btn btn-primary">						<?php print render($content['take']); ?>					</span>				<?php endif;?>				<?php /*print $read_more;*/?>			</div>		</div>	</div></div> <?php if ($page): ?>      <?php      // We hide the comments and links now so that we can render them later.      hide($content['comments']);      hide($content['links']);      hide($content['stats']);      ?>    <?php endif; ?>